import AppController from '../controllers/AppController';
import UsersController from '../controllers/UsersController';
import AuthController from '../controllers/AuthController';
import express from 'express';
const router = express.Router();
router.get('/status', (req, res)=>AppController.getStatus(req, res));
router.get('/stats', (req, res)=>AppController.getStats(req, res));
router.post('/users', async (req, res)=>UsersController.postNew(req, res));
router.get('/connect', async (req, res)=>AuthController.getConnect(req, res));
router.get('/disconnect', async (req, res)=>AuthController.getDisconnect(req, res));
router.get('/users/me', (req, res)=>UsersController.getMe(req, res));
export default router;
